INPUT:
  FRAMES: 3
  HEIGHT: 480
  #1280
  #640
  WIDTH: 640
  #1920
  #960
  SAMPLES: -1
TRAIN:
#  ITERS: [2000, 5000]
  ITERS: [20, 50]
  BATCH: [3, 1]
  LR: 0.001
  CLIP_GRADS: True
MOTION:
  STACK_FRAMES: True
  TRAIN:
    DELTA: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
STRUCTURE:
  MODE: concat
  HG_COUNT: 2
